name: Bug report
description: Report something broken
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What’s wrong?
      description: What happened and what you expected.
      placeholder: "Expected … but got …"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Where does it happen?
      options:
        - Desktop (macOS)
        - Desktop Web
        - Mobile (Web/PWA)
        - VS Code extension
        - Not sure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version (if known)
      placeholder: "e.g. 1.2.3"

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots (optional)
      description: Paste anything relevant (or attach screenshots).
      render: shell
