name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: goal
    attributes:
      label: What do you want to do?
      placeholder: "I want to …"
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: What should OpenChamber do?
      placeholder: "Add/change …"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Extra context (optional)
      description: Links, screenshots, mockups, constraints, etc.
